# markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD033/no-inline-html - Inline HTML
# 允许在 Markdown 中使用内联 HTML（如 <div>, <img> 等）
MD033: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
# 允许第一行不是一级标题（例如可以先放置 HTML 或注释）
MD041: false

# MD013/line-length - 限制单行最大长度
# 与项目的 Prettier printWidth(120) 对齐，避免 README 中长链接/徽章频繁报警
MD013: false

# MD024/duplicate-heading - Duplicate headings
# 允许重复标题，适用于章节内可能出现相同标题的情况
MD024: false